/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (destruction-derby-2-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800696E8u
#define func_800696E8 BootEntry  /* alias */
